language: php
sudo: false
php:
- '5.6'
- '5.5'
- '5.4'
before_install: echo "extension=ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install: make install
script: make lint
after_success: '[[ -n "$TRAVIS_TAG" ]] && make gh-pages'
env:
  global:
    secure: fZXPsnwuJ+OXyWoGmpltUcPbcWdNAic9S8fWuaGIvbSbyrN+blEEnnZzyGTCKabBG7k3yEMgP9URGxrzVv4gIB8l1K9GK2mH82RqBbpaRL/5S3Zn7eN9VCgcN2t5ihMSh9dtDSOdW7zc5j+asQSmppieTLa0UQ5wBPhKbHpixKk=
